<?php

use Illuminate\Database\Seeder;
use App\Asset;

class AssetsTableSeeder extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        $records = [
            [
                1,
                "bibendum ullamcorper. Duis cursus, diam",
                "Mary",
                "8.52",
                "2017-01-27",
                5,
                "O4Z 8B7",
                4,
                1,
                "Nunc ut",
                34,
                1,
                3,
                "2018-07-08",
                3,
                "Stacey",
                "2017-12-17",
                0,
                "DLD48QLXRP",
                2020
            ],
            [
                2,
                "eu neque",
                "Hilary",
                "5.73",
                "2017-10-01",
                2,
                "Q8P 7H4",
                4,
                1,
                "sollicitudin adipiscing ligula.",
                139,
                0,
                5,
                "2017-06-04",
                1,
                "Sara",
                "2017-01-24",
                0,
                "YMQ15QJ5AZ",
                2018
            ],
            [
                3,
                "varius. Nam porttitor scelerisque neque. Nullam",
                "Noah",
                "2.93",
                "2017-07-13",
                3,
                "A6V 2I1",
                5,
                4,
                "mattis semper, dui lectus",
                158,
                1,
                1,
                "2018-02-02",
                2,
                "Griffin",
                "2017-01-10",
                1,
                "YWK78JJ5HZ",
                2019
            ],
            [
                4,
                "Etiam ligula",
                "Alana",
                "6.48",
                "2016-12-22",
                3,
                "N0G 9K9",
                2,
                4,
                "egestas. Fusce",
                221,
                0,
                1,
                "2018-02-24",
                3,
                "Georgia",
                "2017-04-23",
                1,
                "IUC41XA0JC",
                2025
            ],
            [
                5,
                "arcu. Sed et",
                "Avram",
                "6.78",
                "2017-12-31",
                4,
                "C2M 8V4",
                5,
                3,
                "scelerisque scelerisque dui.",
                160,
                0,
                1,
                "2018-05-30",
                2,
                "Deacon",
                "2017-10-22",
                0,
                "AJU13OV8UJ",
                2024
            ],
            [
                6,
                "odio a purus. Duis elementum, dui quis",
                "Rosalyn",
                "2.61",
                "2018-02-07",
                2,
                "Z1C 7Z0",
                1,
                3,
                "sed pede nec ante",
                64,
                0,
                1,
                "2018-10-09",
                2,
                "Jasper",
                "2017-01-03",
                1,
                "KGE89KI6DU",
                2019
            ],
            [
                7,
                "magna. Ut tincidunt orci quis lectus. Nullam, est",
                "Althea",
                "7.57",
                "2018-08-16",
                5,
                "L9T 3Y5",
                5,
                1,
                "lacinia orci, consectetuer euismod est",
                128,
                0,
                4,
                "2018-07-05",
                2,
                "Marvin",
                "2017-09-20",
                1,
                "GLW83AB1OV",
                2025
            ],
            [
                8,
                "lectus sit",
                "Christopher",
                "5.74",
                "2018-08-26",
                1,
                "U9Y 6H2",
                3,
                2,
                "tristique neque venenatis",
                219,
                1,
                2,
                "2017-08-03",
                1,
                "Amity",
                "2018-09-17",
                0,
                "KUU44PCBMV",
                2017
            ],
            [
                9,
                "faucibus orci luctus et ultrices posuere; Donec",
                "Rogan",
                "3.63",
                "2018-03-08",
                3,
                "E5P 2S8",
                2,
                4,
                "neque pellentesque massa lobortis",
                127,
                0,
                3,
                "2018-10-12",
                3,
                "Hedwig",
                "2017-06-25",
                0,
                "EXV74CV0ZZ",
                2021
            ],
            [
                10,
                "pede et risus. Quisque",
                "Caesar",
                "1.58",
                "2017-08-26",
                4,
                "F8O 2P4",
                2,
                4,
                "Donec vitae erat vel",
                171,
                0,
                5,
                "2018-06-27",
                1,
                "Emery",
                "2017-06-24",
                0,
                "YKN72ZQ6NI",
                2018
            ],
            [
                11,
                "sapien imperdiet ornare. In faucibus.",
                "Caleb",
                "6.85",
                "2017-04-16",
                1,
                "N6K 1T6",
                2,
                1,
                "non, feugiat nec, diam. Duis",
                202,
                0,
                4,
                "2018-09-07",
                1,
                "Cora",
                "2018-04-05",
                1,
                "UDO93WDR8G",
                2020
            ],
            [
                12,
                "Nunc sed orci lobortis",
                "Nathan",
                "3.95",
                "2016-11-24",
                2,
                "Q5Y 8W3",
                4,
                1,
                "a, malesuada id, erat. Etiam",
                81,
                0,
                1,
                "2018-09-13",
                2,
                "Damian",
                "2018-05-03",
                0,
                "QM48OHY0NI",
                2018
            ],
            [
                13,
                "porttitor interdum. Sed auctor odio a",
                "Selma",
                "2.10",
                "2018-06-05",
                4,
                "X5T 3A1",
                1,
                2,
                "Nunc mauris. Morbi",
                105,
                0,
                3,
                "2017-07-02",
                3,
                "Freya",
                "2017-10-30",
                0,
                "EFH52JMO6M",
                2019
            ],
            [
                14,
                "Duis cursus, diam at pretium aliquet, metus erat",
                "Gloria",
                "1.23",
                "2017-01-29",
                2,
                "U2V 1A7",
                2,
                4,
                "dictum mi, ac mattis",
                121,
                0,
                1,
                "2017-12-08",
                2,
                "Jerome",
                "2018-09-18",
                1,
                "DCT55JIU2C",
                2018
            ],
            [
                15,
                "lobortis risus. In mi pede, nonummy ut, molestie",
                "Oprah",
                "1.76",
                "2017-01-31",
                3,
                "D9X 1F4",
                4,
                3,
                "faucibus leo, in lobortis tellus",
                124,
                0,
                5,
                "2018-01-07",
                5,
                "Barclay",
                "2018-03-15",
                1,
                "EQH65GTE4L",
                2018
            ],
            [
                16,
                "sem. Pellentesque ut ipsum ac mi eleifend egestas.",
                "Jade",
                "8.02",
                "2017-06-20",
                5,
                "U7B 7Q0",
                2,
                4,
                "id enim. Curabitur massa.",
                125,
                1,
                1,
                "2017-12-22",
                3,
                "Bruno",
                "2018-09-15",
                1,
                "LAR03LAD1M",
                2022
            ],
            [
                17,
                "diam vel arcu. Curabitur ut odio vel est tempor",
                "Britanni",
                "2.07",
                "2016-12-24",
                5,
                "J6Y 6N0",
                5,
                4,
                "Fusce",
                220,
                0,
                5,
                "2018-11-02",
                2,
                "Sybill",
                "2017-03-16",
                0,
                "ZLH43DGE0L",
                2024
            ],
            [
                18,
                "ut",
                "Amal",
                "1.27",
                "2017-05-17",
                4,
                "G1C 2N9",
                1,
                3,
                "lobortis",
                235,
                0,
                5,
                "2018-02-25",
                5,
                "Risa",
                "2018-04-27",
                0,
                "TZD23DXK0U",
                2022
            ],
            [
                19,
                "molestie. Sed id risus quis diam luctus lobortis.",
                "Nolan",
                "2.25",
                "2018-08-21",
                2,
                "G1I 9I7",
                5,
                1,
                "ridiculus",
                155,
                1,
                3,
                "2018-06-05",
                4,
                "Eleanor",
                "2017-06-13",
                0,
                "IPG08DQI2O",
                2022
            ],
            [
                20,
                "rutrum",
                "Basil",
                "3.25",
                "2016-12-25",
                5,
                "Y7H 2K2",
                3,
                3,
                "mi enim, condimentum eget, volutpat",
                195,
                1,
                3,
                "2018-04-28",
                5,
                "Winter",
                "2018-08-16",
                0,
                "EAU79FKK8Y",
                2023
            ]
        ];

        $count = count($records);

        foreach ($records as $key => $record) {
            Asset::insert([
                'created_at' => Carbon\Carbon::now()->subDays($count)->toDateTimeString(),
                'updated_at' => Carbon\Carbon::now()->subDays($count)->toDateTimeString(),
                'id' => $record[0],
                'description' => $record[1],
                'owner' => $record[2],
                'purchase_price' => $record[3],
                'purchase_date' => $record[4],
                'group_id' => $record[5],
                'serial_number' => $record[6],
                'location_id' => $record[7],
                'warranty_id' => $record[8],
                'notes' => $record[9],
                'estimated_life_months' => $record[10],
                'is_out_of_service' => $record[11],
                'out_of_service_id' => $record[12],
                'out_of_service_date' => $record[13],
                'vendor_id' => $record[14],
                'assigned_to' => $record[15],
                'assigned_date' => $record[16],
                'is_computer' => $record[17],
                'tag' => $record[18],
                'scheduled_retirement_year' => $record[19]
            ]);
            $count--;
        }
    }
}
